export const __GAME_LIST__ = [
  {
    category: 'comming_soon',
    games: [
      {
        key: 'caesar',
        volatility: 'medium',
        rtp: 96.83,
        maxwin: 2027,
        betways: 25,
      },
      {
        key: 'shogun',
        volatility: 'low',
        rtp: 96.0,
        maxwin: 805.5,
        betways: 243,
      },
      {
        key: 'pharaoh',
        volatility: 'low',
        rtp: 96.24,
        maxwin: 1800,
        betways: 10,
      },
      {
        key: 'commando',
        volatility: 'low',
        rtp: 95.93,
        maxwin: 2263,
        betways: 46656,
      },
      {
        key: 'gold_rush',
        volatility: 'medium',
        rtp: 96.4,
        maxwin: 3048,
        betways: 20,
      },
      {
        key: 'speed_and_fury',
        volatility: 'medium',
        rtp: 96.78,
        maxwin: 3300,
        betways: 3125,
      },
      {
        key: 'wild_catch',
        volatility: 'medium',
        rtp: 96.72,
        maxwin: 30000,
        betways: 720,
      },
    ],
  },
  {
    category: 'legends',
    games: [
      {
        key: 'athena_vs_ares',
        url: 'https://demo.cyberyokai.com/cyplay/slots/athena-vs-ares/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 95.39,
        maxwin: 4000,
        betways: 30,
      },
      {
        key: 'olympus_risen',
        url: 'https://demo.cyberyokai.com/cyplay/slots/olympus-risen/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.68,
        maxwin: 11237,
        betways: 117649,
      },
      {
        key: 'zeus_legacy',
        url: 'https://demo.cyberyokai.com/cyplay/slots/zeus-legacy/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 95.51,
        maxwin: 11237,
        betways: 117649,
      },
    ],
  },
  {
    category: 'blockbuster',
    games: [
      {
        key: 'cop_buddies',
        url: 'https://demo.cyberyokai.com/cyplay/slots/cop-buddies/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 97.44,
        maxwin: 150000,
        betways: 20,
      },
    ],
  },
  {
    category: 'indo_local',
    games: [
      {
        key: 'joss_joss_joss',
        url: 'https://demo.cyberyokai.com/cyplay/slots/vanilla-joss/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.95,
        maxwin: 100000,
        betways: 2000,
      },
      {
        key: 'energ_super_laga',
        url: 'https://demo.cyberyokai.com/cyplay/slots/energ-superlaga/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.98,
        maxwin: 11237,
        betways: 117649,
      },

      {
        key: 'gali_mania',
        url: 'https://demo.cyberyokai.com/cyplay/crash-game/gali-mania/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 94.88,
        maxwin: 5000,
        betways: 'Crash',
      },
      {
        key: 'nabung_tap_tap',
        url: 'https://demo.cyberyokai.com/cyplay/taptap/celengan-taptap/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.98,
        maxwin: 6050,
        betways: 'Crash',
      },
    ],
  },
  {
    category: 'supercell',

    games: [
      {
        key: 'coc_reborn',
        url: 'https://demo.cyberyokai.com/cyplay/slots/coc-reborn/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 95.51,
        maxwin: 5000,
        betways: 'Pay any',
      },
      {
        key: 'clash_heroes',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-clash-heroes?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.78,
        maxwin: 2992,
        betways: 36,
      },
      {
        key: 'coc',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-coc?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.83,
        maxwin: 2027,
        betways: 25,
      },
    ],
  },
  {
    category: 'reskin',

    games: [
      {
        key: 'ahri',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-ahri?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 95.05,
        maxwin: 400,
        betways: 1,
      },
      {
        key: 'akali',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-akali?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.01,
        maxwin: 1000,
        betways: 50,
      },
      {
        key: 'arcane',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-arcane?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.24,
        maxwin: 1250.8,
        betways: 50,
      },

      {
        key: 'evelynn',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-evelynn?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.0,
        maxwin: 2079,
        betways: 720,
      },
      {
        key: 'hayabusa',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-hayabusa?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96,
        maxwin: 805.5,
        betways: 243,
      },
      {
        key: 'kagura',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-kagura?useMock=true&enableCheat=true',
        volatility: 'low',
        rtp: 96.18,
        maxwin: 5000,
        betways: 15,
      },
      {
        key: 'kaisa',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-kaisa?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.06,
        maxwin: 3000,
        betways: 40,
      },
      {
        key: 'nasus',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-nasus?useMock=true&enableCheat=true',
        volatility: 'low',
        rtp: 96.24,
        maxwin: 1800,
        betways: 10,
      },
      {
        key: 'seraphine',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-seraphine?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.18,
        maxwin: 1000,
        betways: 5,
      },
    ],
  },
  {
    category: 'campaign',
    games: [
      {
        key: 'dota',
        url: 'https://demo.cyberyokai.com/cyplay/slots/dota-campaign/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: 96.83,
        maxwin: 2027,
        betways: 25,
      },
    ],
  },
];
