export const __GAME_LIST__ = [
  {
    category: 'legends',
    games: [
      {
        key: 'athena_vs_ares',
        url: 'https://demo.cyberyokai.com/cyplay/slots/athena-vs-ares/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'olympus_risen',
        url: 'https://demo.cyberyokai.com/cyplay/slots/olympus-risen/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'zeus_legacy',
        url: 'https://demo.cyberyokai.com/cyplay/slots/zeus-legacy/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
    ],
  },
  {
    category: 'blockbuster',
    games: [
      {
        key: 'cop_buddies',
        url: 'https://demo.cyberyokai.com/cyplay/slots/cop-buddies/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
    ],
  },
  {
    category: 'indo_local',
    games: [
      {
        key: 'joss_joss_joss',
        url: 'https://demo.cyberyokai.com/cyplay/slots/vanilla-joss/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'energ_super_laga',
        url: 'https://demo.cyberyokai.com/cyplay/slots/energ-superlaga/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'nabung_tap_tap',
        url: 'https://demo.cyberyokai.com/cyplay/taptap/celengan-taptap/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'gali_mania',
        url: 'https://demo.cyberyokai.com/cyplay/crash-game/gali-mania/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
    ],
  },
  {
    category: 'supercell',
    games: [
      {
        key: 'coc_reborn',
        url: 'https://demo.cyberyokai.com/cyplay/slots/coc-reborn/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'clash_heroes',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-clash-heroes?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'coc',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-coc?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
    ],
  },
  {
    category: 'reskin',

    games: [
      {
        key: 'ahri',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-ahri?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'akali',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-akali?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'arcane',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-arcane?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'dota',
        url: 'https://demo.cyberyokai.com/cyplay/slots/dota-campaign/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'evelynn',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-evelynn?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'hayabusa',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-hayabusa?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'kagura',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-kagura?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'kaisa',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-kaisa?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'nasus',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-nasus?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
      {
        key: 'seraphine',
        url: 'https://demo.cyberyokai.com/cyplay/slots/reskin-seraphine?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
    ],
  },
  {
    category: 'campaign',
    games: [
      {
        key: 'dota',
        url: 'https://demo.cyberyokai.com/cyplay/slots/dota-campaign/?useMock=true&enableCheat=true',
        volatility: 'medium',
        rtp: null,
        maxwin: null,
        betways: null,
      },
    ],
  },
];
